#!/usr/bin/bash

#if parameter count is not 2
if [ $# -ne 2 ]; then
	echo "Invalid parameter count '$#' to 'termux_tasker_basic_bash_test'" 1>&2
	echo "$*" 1>&2
	exit 1
fi

echo "\$1=\`$1\`"
echo "\$2=\`$2\`"

exit 0
